#!/usr/bin/node

let request = require("request");
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

request(url, function(error, response, body){
	let { document } = (new JSDOM(body)).window;

	let paragraphs = document.querySelectorAll("p");
	let references = document.querySelectorAll(".reference");

	references.forEach(function(reference){
		reference.remove();
	});

	paragraphs.forEach(function(paragraph){
		console.log(paragraph.textContent);
	});
});
